name: Shell command

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: eco "Hello world"
      - name: multiline script
        run: |
          node -v
          npm -v